pulumi/pulumi-terraform-module

pkg/modprovider/module_component.go
pkg/modprovider/state.go
pkg/tfsandbox/state.go
pkg/tfsandbox/state_test.go

This PR adds the Tofu
[lockfile](https://opentofu.org/docs/language/files/dependency-lock/) to
the ModuleState resource. Now whenever we push/pull state we also
push/pull the lockfile. Using the lockfile will ensure that every time
we run tofu we will always select the same version of the providers.
One thing to note is that when the lockfile is created during `tofu init` it has a `h1:` checksum and a bunch of `zh:` checksums. The `zh:` checksums are the checksums for each platform supported by that provider and the `h1:` checksum is the checksum created for the local platform. So this is a scenario that could happen
1. User runs terraform init on `macos`
2. `h1:` entry created for `macos`
3. Terraform run in CI on linux machine
4. Terraform picks the version of the provider based on the …

Save tofu lockfile to preserve provider choices

---

pkg/modprovider/logger.go
pkg/modprovider/module_component.go
pkg/modprovider/server.go
pkg/modprovider/state.go
pkg/modprovider/tfmodules.go
pkg/modprovider/tfmodules_test.go
pkg/tfsandbox/apply.go
pkg/tfsandbox/destroy.go
pkg/tfsandbox/init.go
pkg/tfsandbox/log.go
pkg/tfsandbox/plan.go
pkg/tfsandbox/refresh.go
pkg/tfsandbox/state_test.go
pkg/tfsandbox/tofu_test.go
tests/schema_create_secrets_test.go
tests/schema_create_test.go

These changes add support for streaming logs from tofu operations back to the Pulumi engine. The engine will render these logs during previews and updates, where they will be associated with the module's component resource. This makes it easier to understand what is happening during active periods that have no associated resource operations (e.g. while `plan` or `apply` is running).

[ux] Stream logs from tofu

---

tests/acc_test.go
tests/testdata/programs/python/s3bucketmod/.gitignore
tests/testdata/programs/python/s3bucketmod/Pulumi.yaml
tests/testdata/programs/python/s3bucketmod/__main__.py
tests/testdata/programs/python/s3bucketmod/requirements.txt

This is a basic end-to-end test for the purposes of verifying that:
- the Python SDK generates correctly via `pulumi package add`
- The generated SDK works in a small test module, in this case AWS Bucket.
What this test is *not*:
- A comprehensive real-world example on how to use the AWS Bucket module in Python (although we could upgrade it to that in the future).
Part of https://github.com/pulumi/pulumi-terraform-module/issues/94.

Add Python end to end test

---

pkg/modprovider/module_component.go
pkg/tfsandbox/details.go
pkg/tfsandbox/state_test.go
pkg/tfsandbox/testdata/modules/test_module/outputs.tf
pkg/tfsandbox/testdata/modules/test_module/variables.tf
pkg/tfsandbox/tf_file.go

This is a fix for the inconsistent plan error.
To expose outputs from a module, we need to account for the secretness of the outputs
If you try and output a secret value without setting `sensitive: true` in the output
The deployment will fail. We also need to be able to handle this dynamically since we won't know
the secret status until after the operation, and we need to write the output definition when we create the file (before the operation).
In #132 we added support for module outputs by using a `terraform_data` resource as a proxy for the output. This allowed us to account for the dynamic nature of the secret since we could determine the secret status of the value using the same method that we use for all other resource properties.
This ran into an issue #198 where `terraform_data` …

Fix inconsistent plan error

---

pkg/tfsandbox/tofu.go

I keep running into CI flakes with an error on the `Test_TwoInstances_TypeScript` test.
```console
error: randmod:index:Module resource 'myrandmod2' has a problem: NewModuleComponentResource failed: Init failed: error running tofu init: exit status 1
```
It seems to happen when there is not a already existing temp folder for both modules (which is always the case for CI). I think it is due to using the shared plugin cache so turning it off for now so I can revisit it after our CI stops failing.
re #199

Remove TF_PLUGIN_CACHE_DIR usage

---

pkg/tfsandbox/plan.go

Follow up to #222 to add the human readable plan to the debug log
output.
fixes #216

Log the human readable plan to debug log

---

examples/aws-eks-example/Pulumi.yaml
examples/aws-eks-example/README.md
examples/aws-eks-example/index.ts
examples/aws-eks-example/kube-config.ts
examples/aws-eks-example/package.json
tests/examples_test.go

Adds an example test for using the aws eks Terraform module
re #211

Add eks example test

---

tests/acc_test.go
tests/testdata/programs/ts/rdsmod/Pulumi.yaml
tests/testdata/programs/ts/rdsmod/index.ts
tests/testdata/programs/ts/rdsmod/package.json

Due to Create and Destroy times being > 5 minutes each, this test verifies Preview only.
Fixes #40

Add basic e2e test for RDS module

---

pkg/modprovider/server_test.go
pkg/modprovider/tfmodules.go
pkg/modprovider/tfmodules_test.go
pkg/tfsandbox/tf_file.go

This pull request makes a slight adjustment to the source parsing switch in `tfmodules.go` to also accept `addrs.ModuleSourceRemote`. These non-registry, remote modules all only take a `source` argument, but not a `version` argument.
It adds tests to verify that a non-registry-based, remote, module source can be resolved, can have its schema inferred, and is accepted by `tofu.Init`.
This means that 
`pulumi package add terraform-module github.com/username/modulename demo-website` 
is now valid input.
More tests are added to support the newly added parsing behavior. 
The remote example used is a third-party demo repo: https://github.com/yemisprojects/s3_website_module_demo
What this pull request does **not** do:
- Tests for non-GitHub remote module sources (mostly because a good example is …

Accept all remote module sources in parameterize call

---

pkg/modprovider/module_component.go
pkg/tfsandbox/apply.go
tests/acc_test.go
tests/testdata/programs/ts/partial-apply/Pulumi.yaml
tests/testdata/programs/ts/partial-apply/index.ts
tests/testdata/programs/ts/partial-apply/local_module/main.tf
tests/testdata/programs/ts/partial-apply/local_module/outputs.tf
tests/testdata/programs/ts/partial-apply/local_module/variables.tf
tests/testdata/programs/ts/partial-apply/package.json

This PR handles the case where `tofu apply` fails, but some resources
have been provisioned. As long as we can read the TF state file we will
continue to process the child resources and only after they have been
processed will we fail the component.
This is what a partial deployment will look like now (based on the
example test added).
```console
Previewing update (chall)
View in Browser (Ctrl+O): https://app.pulumi.com/chall-pulumi-corp/partial-apply/chall/previews/b0d1e4be-9ef0-4f84-9211-a241baed39fa
Type                                              Name                                                      Plan       Info
+   pulumi:pulumi:Stack                               partial-apply-chall                                       create     2 warnings
+   └─ localmod:index:Module …
```

Handle partial failures in tofu apply

---

tests/schema_create_test.go

The resource we use `aws_s3_bucket_lifecycle_configuration` was migrated
upstream from sdkv2 to pf so the schema changed a little

Fix schema tests diff

---

pkg/tfsandbox/tofu.go
pkg/tfsandbox/tofu_test.go
pkg/tofuresolver/installer.go
pkg/tofuresolver/package.go
pkg/tofuresolver/resolver.go
pkg/tofuresolver/resolver_test.go

Auto-installing and resolving tofu executable is a slightly separate concern from tfsandbox so putting it into a
dedicated Go package here. This also allows using it to test more Go packages that need a tofu executable for testing,
besides tofusandbox package itself.

chore: factor out tofuresolver

---

README.md
pkg/modprovider/child.go
pkg/modprovider/module_schema_overrides/README.md
pkg/modprovider/module_schema_overrides/example-schema.json
pkg/modprovider/module_schema_overrides/terraform-aws-vpc.json
pkg/modprovider/params.go
pkg/modprovider/schema.go
pkg/modprovider/server.go
pkg/modprovider/server_test.go
pkg/modprovider/testdata/module_configuration/simple-config.json
pkg/modprovider/tfmodules.go
pkg/modprovider/tfmodules_test.go
tests/testdata/aws-vpc/java/sdks/vpc/src/main/java/com/pulumi/vpc/Module.java
tests/testdata/aws-vpc/node/sdks/vpc/module.ts

This PR addresses #70 by allow us to override inferred schema using configuration files for the following use cases:
Providing schema overrides for known modules (e.g. for top N common AWS modules), typically authored by us and added to this repository in the `pkg/modprovider/module_schema_overrides` directory. These will automatically apply for users without their intervention such that the generated SDKs have the correct types. 
> Right now, I have not started creating a catalogue of these schemas but the ability is there.
See [docs](https://github.com/pulumi/pulumi-terraform-module/blob/7e0d17ae6b56c4703db7f47e1423ce15ebc74776/pkg/modprovider/module_schema_overrides/README.md) about these known-schema config files
Available via `--config <path-to-config-file.json>` when using the …

Allow for module configuration and schema override

---

README.md
docs/config-reference.md

Shortened the top-level README by moving config reference under docs.
Linked the override registry from top-level README.
Linked the experimental tool.
Added links to Pulumi Package Schema to the config reference.

Refine docs

---

pkg/modprovider/helpers_test.go
pkg/modprovider/logger.go
pkg/modprovider/module_component.go
pkg/modprovider/state.go
pkg/modprovider/tfmodules.go
pkg/tfsandbox/helpers_test.go
pkg/tfsandbox/plan.go
pkg/tfsandbox/state.go
pkg/tfsandbox/tf_file.go
pkg/tfsandbox/tf_file_test.go
pkg/tfsandbox/tofu.go
pkg/tfsandbox/workdir.go
pkg/tfsandbox/workdir_test.go
tests/acc_test.go
tests/examples_test.go
tests/helper_test.go

Workspace files are retained across `pulumi up`  invocations, matching the expectation of modules such as the AWS Lambda Terraform Module to be able to persist information in the file system across invocations. 
Fixes #166 
As a side fix, DEBUG level logs no longer show through the product UI by default. This seems to have been an unintentional omission to send them at INFO level.

Simpler workdir cleanup

---

pkg/modprovider/module_schema_overrides/cloudposse-label.json
pkg/modprovider/module_schema_overrides/terraform-aws-acm.json
pkg/modprovider/module_schema_overrides/terraform-aws-alb.json
pkg/modprovider/module_schema_overrides/terraform-aws-eks.json
pkg/modprovider/module_schema_overrides/terraform-aws-kms.json
pkg/modprovider/module_schema_overrides/terraform-aws-rds-aurora.json
pkg/modprovider/module_schema_overrides/terraform-aws-rds.json
pkg/modprovider/module_schema_overrides/terraform-aws-s3-bucket.json
pkg/modprovider/module_schema_overrides/terraform-aws-vpc.json
pkg/modprovider/module_schema_overrides/terraform-azurerm-virtualnetwork.json
pkg/modprovider/module_schema_overrides/terraform-google-kubernetes-engine.json
pkg/modprovider/module_schema_overrides/terraform-google-network.json
pkg/modprovider/module_schema_overrides/terraform-google-project-factory.json
pkg/modprovider/tfmodules.go

This PR adds a number of module schema overrides for popular TF modules, used https://library.tf/modules to see which modules are the most popular by number of downloads, then using [infer-tfmodule-schema](https://github.com/pulumi/pulumi-tool-infer-tfmodule-schema) to infer the outputs, at least the non-string ones.
Fixes #214 (override added for that specific module)

Add initial list of module schema overrides

---

pkg/modprovider/server.go
pkg/modprovider/server_test.go

This pull request adds the ability to unwrap a secreted config value in cleanProvidersConfig.
Currently, a config object wrapped in a secret would fail as an unsupported type. But part of the logic in https://github.com/pulumi/pulumi-terraform-bridge/pull/3007 wraps the `terraformConfig().return` object in a secret. This object is already properly formatted to be usable by Terraform; so all we need to do is return the secret's value.
A potential concern is that any user-provided secret config inputs would also hit this line, and perhaps not get cleaned up properly. I'm not sure how much of a concern that should be - the alternative is running two separate passes over `s.providerConfig`.
Prerequisite for https://github.com/pulumi/pulumi-terraform-bridge/pull/3007 .

Unwrap secreted configs in cleanProvidersConfig

---

.ci-mgmt.yaml
.github/workflows/publish.yml
.github/workflows/test.yml

Noticing that sometimes PRs take 50 minutes to verify, hoping this small tweak will help us cut this time, at the cost of using more runners.

chore: double test shards to check PRs faster

---

.ci-mgmt.yaml
.github/workflows/main.yml
.github/workflows/publish.yml

Without this the workflow to verify that the tests still run on every commit to the main branch was not being activated.

chore: fix default branch

---

pkg/modprovider/child.go
pkg/modprovider/child_test.go
pkg/modprovider/module_component.go
pkg/modprovider/planstore.go
pkg/modprovider/planstore_test.go
pkg/modprovider/resources.go
pkg/tfsandbox/apply.go
pkg/tfsandbox/details.go
pkg/tfsandbox/details_test.go
pkg/tfsandbox/plan.go
pkg/tfsandbox/plan_test.go
pkg/tfsandbox/refresh.go
pkg/tfsandbox/resources.go
pkg/tfsandbox/state_test.go
pkg/tfsandbox/testdata/plans/delete_plan.json
tests/schema_create_test.go

When working on the views feature I found that *tfsandbox.ResourcePlan object does not represent resource deletions. This is now fixed, and the ResourceStateOrPlan abstraction is removed as it is confusing and generally the two are not interchangeable.

Refactor resource plans

---

pkg/tfsandbox/details.go
pkg/tfsandbox/details_test.go
pkg/tfsandbox/testdata/plans/plan_with_datasource_changes.json

Recent change in https://github.com/pulumi/pulumi-terraform-module/pull/336 introduced a subtle problem. Sometimes TF includes data source calls in the plan structure under ResourceChanges field. For the purposes of this codebase the data source plans are not needed or expected. Before these change they were rendered as incorrect resource operation plans. After the change they are ignored.

Exclude data sources from plans

---

pkg/modprovider/server.go
pkg/modprovider/server_test.go
pkg/modprovider/tfmodules_test.go
pkg/tfsandbox/tf_file.go
pkg/tfsandbox/types.go

Resolves #369 
Extracting module version from git / URL sources that define the version in `?ref=<version>` query parameter and ensuring that we don't set an explicit version in the TF file we write because a version is only valid for registry-based modules.

Infer version from git and URL based module sources

---

pkg/modprovider/error_message.go
pkg/modprovider/error_messages/aws_missing_credentials_error.txt
pkg/modprovider/logger.go
tests/acc_test.go

Resolves #197 
When using terraform AWS modules without credentials, we see an error that is terraform-specific and not actionable for Pulumi users. This missing credentials error is issued as an error log message. This PR intercepts logs to detect that error and return a nicer Pulumi-specific error similar to how we implemented it in pulumi-aws.

Better missing credentials error when using AWS modules

---

README.md

Update README to match recent changes for defaulting to `terraform`.

Update README for executor changes.

---

pkg/modprovider/tfmodules.go
tests/acc_test.go
tests/testdata/aws-vpc/go-views/sdks/vpc/vpc/module.go
tests/testdata/aws-vpc/go-views/sdks/vpc/vpc/provider.go
tests/testdata/aws-vpc/java-views/sdks/vpc/src/main/java/com/pulumi/vpc/Module.java
tests/testdata/aws-vpc/java-views/sdks/vpc/src/main/java/com/pulumi/vpc/ProviderArgs.java
tests/testdata/aws-vpc/node-views/sdks/vpc/module.ts
tests/testdata/aws-vpc/node-views/sdks/vpc/provider.ts
tests/testdata/aws-vpc/node-views/sdks/vpc/utilities.ts

This PR resolves #329 where language SDKs report runtime errors when there are type mismatches between the output types in the schema and the actual runtime types. 
Previously we have used `string` to be the default but there many output shapes that are not strings so this PR changes the default to be `any`. Users would have to cast the output properties they care about into the appropriate type to use it which is a slight inconvenience but better than erroring out from and getting stuck.
This PR also handles a few cases of `try(...)` expressions used in output values to determine their types. For example expressions of the form:
- `try(<expr1>, <expr2>, ..., "")` would resolve to a `string` type because the default here is the last expression being a string literal
- `try(<expr1>, …

Default output type is any, better inference for try(...) expressions

---

examples/aws-rds-example/index.ts
pkg/modprovider/module.go
pkg/modprovider/server.go
pkg/tfsandbox/plan.go
tests/acc_test.go
tests/examples_test.go
tests/testdata/modules/changing_module_source_outputs/mod_v1/main.tf
tests/testdata/modules/changing_module_source_outputs/mod_v2/main.tf
tests/testdata/modules/changing_module_source_resources/mod_v1/main.tf
tests/testdata/modules/changing_module_source_resources/mod_v2/main.tf
tests/testdata/programs/yaml/changing_module_source_outputs/Pulumi.yaml
tests/testdata/programs/yaml/changing_module_source_resources/Pulumi.yaml

- Resolves [Pulumi does not see changes to local modules](https://github.com/pulumi/pulumi-terraform-module/issues/391)
- Maybe addresses [[views] failed to detect changes that tofu plan would detect](https://github.com/pulumi/pulumi-terraform-module/issues/350)
This PR makes sure that changes in the underlying module are detected in `Diff(...)` such that communicate to the engine that an `Update(...)` is needed. We do so by performing a `terraform plan` within `Diff(...)` and check if
- any resource has a change that is _not_ a No-Op => resources have changed => return `DIFF_SOME`
- any output has a change that is _not_ No-Op => outputs have changed => return `DIFF_SOME`
We only perform a `plan` after we have checked that the inputs haven't changed. If the inputs have changed, then a …

Ensure module changes are detected in Diff(...)

---

go.mod
go.sum
tests/acc_test.go

Update Pulumi to v3.177.0. This enables YAML programs without having to specify `PULUMI_ENABLE_VIEWS_PREVIEW`.
Fixes #403

dependencies: pulumi v3.177.0

---

examples/azure-vnet-example/.gitignore
examples/azure-vnet-example/Pulumi.yaml
examples/azure-vnet-example/README.md
examples/azure-vnet-example/index.ts
examples/azure-vnet-example/package.json
examples/azure-vnet-example/tsconfig.json
pkg/modprovider/server.go
tests/examples_test.go

Emit empty features { } block for default azurerm provider when it is not explicitly configured (default provider) because otherwise `azurerm` modules requires explicit providers always. 
Added an integration test that works locally. Not sure if CI exposes `ARM_SUBSCRIPTION_ID` because it is needed for the test to run. 
Note: the module will error out if `ARM_SUBSCRIPTION_ID` is not available but it will say that `subscription_id` is missing from the provider config which can be a bit misleading. 
Fixes #410

Emit empty features block for default azurerm provider without configuring one explicitly

---

tests/examples_test.go

Bumped the version of the EKS module used in tests as it was broken by the latest terrafrom-provider-aws release (see [fix: Restrict AWS provider max version due to v6 provider breaking changes · terraform-aws-eks/3384](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3384))

bump eks module version to avoid breaking changes due to terrafrom-provider-aws v6.0.0 release

---

pkg/modprovider/module.go
pkg/modprovider/views.go
tests/acc_test.go
tests/testdata/programs/ts/partial-apply/index.ts
tests/testdata/programs/ts/partial-apply/local_module/main.tf
tests/testdata/programs/ts/partial-apply/local_module/variables.tf

Following the suggestion in https://github.com/pulumi/pulumi-terraform-module/issues/342#issuecomment-2987099194 to report partial errors. 
Expanded the tests for partial apply to also exercise generate errors during an update. Includes additional fixes from @justinvp's to how `update` reports views and to how we identify failing view steps, particularly for replacements.
fixes: https://github.com/pulumi/pulumi-terraform-module/issues/386
related: https://github.com/pulumi/pulumi/issues/19635, https://github.com/pulumi/pulumi-terraform-module/issues/342 (We may need additional testing on delete and refresh before declaring these issues complete)

Report partial errors on create and update

---

pkg/modprovider/logger.go

`pulumi package add terraform module ...` used to print "Using Terraform CLI for schema inference" to stdout. This is now fixed. The root cause is that DEBUG level messages were sent at INFO level to the engine on the wire by mistake.

Fix emitting warning status logs as visible messages
